### PR TITLE
Kriselda/winecheesepair1

### PR DESCRIPTION
**Pull request by kbonifacio**
added more product pairs to seeded data

### CODE REVIEW

**Review by richardedwardbrown3 — COMMENTED** [review]
Nice pairs

**Review by Felix-Cadiz — COMMENTED** [review]
Same comment as the previous branch, more explanation is needed for the altered routes in components/App.js

**Comment by kbonifacio** [comment]
I may have lost all the Account route through the merge. 
The Cheeses, Wines, and Pairings routes were removed and condensed into /products since the NavLinks in <Products /> now utilize the searchParams given the type of product. The other routes are no longer needed.

**Review by Felix-Cadiz — COMMENTED** [review]
With the deletion of the wine, cheese, product pairs routes, are we going to eventually change the navBar links to filter settings for the searchParams? Or simply have everything in one page?

**Review by Felix-Cadiz — APPROVED** [review]
LGTM!

**Pull request merged**
